export const BOTAO__REQUEST = "BOTAO__REQUEST";
export const BOTAO__SUCCESS = "BOTAO__SUCCESS";
export const BOTAO__FAILURE = "BOTAO__FAILURE";

// login

export const LOGIN__REQUEST = "LOGIN__REQUEST";
export const LOGIN__SUCCESS = "LOGIN__SUCCESS";
export const LOGIN__FAILURE = "LOGIN__FAILURE";

// register

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_UPDATE_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_CREATE_SUCCESS = "REGISTER_SUCCESS";

export const PERSIST_REHYDRATE = "persist/REHYDRATE";
